# description
name: "RitDye™ Calculator"
description: "Ingredient calculator for RitDye™ dye."
keywords: "ritdye, dye, calculator, dye calculator"
author: "Leszek Pietrzak"
logo: "dye-logo.png"

# address settings
baseurl: "http://rdc.magicznyleszek.xyz"

# site configuration
safe: true
quiet: false
future: true
encoding: utf-8
markdown: kramdown
kramdown:
    auto_ids: false
timezone: Europe/Warsaw
port: 2038
